#include "itemtype.hxx"


//MAP EFFECTS

static LONG ItemEffects::MapHighlightEnemies(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::MapHighlightTreasure(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::MapHighlightEvil(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::MapHighlightMagic(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


static LONG ItemEffects::MapHighlightTraps(LONG Combo,LONG Arg,LONG Action)
{
return 0;}
	
static LONG ItemEffects::MapHighlightSecretDoors(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



static LONG ItemEffects::MapTeleport(LONG Combo,LONG Arg,LONG Action)
{
return 0;}






