#include "itemtype.hxx"

//Relics of Power!
static LONG ItemEffects::ChaliceOfDead(LONG Combo,LONG Arg,LONG Action)
{return 0;}


static LONG ItemEffects::TomePrince(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


static LONG ItemEffects::Corgandal(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


static LONG ItemEffects::Danica(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::HammerOfThunder(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
static LONG ItemEffects::SwordOfRoele(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::CandleOfInvocation(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}



/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::AmuletInspiration(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::BannerOfRoele(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}



/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::CrownOfCommand(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::SceptreCuiraeecn(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}
static LONG ItemEffects::BarazadsTools(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


static LONG ItemEffects::FaelesRing(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::GavelonStaff(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::DierdriensRing(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


static LONG ItemEffects::BrennasFavor(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::StateCrownAnnuire(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::EmperorsCrown(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::FaridsCoffer(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::RingOfWizardry(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::RobesOfMasses(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::RegaliaEmpire(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::SielGemLarge(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::SielGemSmall(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}


static LONG ItemEffects::NappolansTome(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::VaubenelsBook(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}

static LONG ItemEffects::TorcSplendor(LONG Combo,LONG Arg,LONG Action)
{
	return OK; //everything went ok	
}










