/* ========================================================================
   Copyright (c) 1990,1996   Synergistic Software
   All Rights Reserved.
   =======================================================================
   Filename: SpelType.cpp -Effects for Spells
   Author: Wes Cumberland
   ======================================================================== */
#include "itemtype.hxx"


static LONG ItemEffects::Jump(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::Strength(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::StoneSkin(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


static LONG ItemEffects::BarkSkin(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::MagicalVestement(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::Shrink(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


static LONG ItemEffects::MagicMissileSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}
											
static LONG ItemEffects::IceStormSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::ConeOfColdSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::ChainLightningSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::DeathSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::Blindness(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::PowerBlindSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::MeteorSwarmSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::PowerKillSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::TimeStopSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::FireStormSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */

static LONG ItemEffects::HolyWordSpell(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::MapShowAll(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



static LONG ItemEffects::LocateObject(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::TurnUndead(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::StoneUndead(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


static LONG ItemEffects::FleshToStone(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::ResistFire(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::SpritualHammer(LONG Combo,LONG Arg,LONG Action)
{
return 0;}


static LONG ItemEffects::ProtectionFromEvil(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::Disintigrate(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::SpellImmunity(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::FlameStrike(LONG Combo,LONG Arg,LONG Action)
{
return 0;}




static LONG ItemEffects::Shillelagh(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



static LONG ItemEffects::GlobeInvulnerability(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::ShockingGrasp(LONG Combo,LONG Arg,LONG Action)
{
return 0;}




static LONG ItemEffects::Confusion(LONG Combo,LONG Arg,LONG Action)
{
return 0;}




static LONG ItemEffects::Knock(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

/* -----------------------------------------------------------------

   ----------------------------------------------------------------- */
static LONG ItemEffects::UndeadTurn(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



//Not used.
static LONG ItemEffects::ImprovedFireball(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

static LONG ItemEffects::ActInfravision(LONG Combo,LONG Arg,LONG action)
{
return 0;}


static LONG ItemEffects::Resurrection(LONG Combo,LONG Arg,LONG Action)
{
return 0;}



static LONG ItemEffects::WaterWalk(LONG Combo,LONG Arg,LONG Action)
{
return 0;}

